apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "binance-chain-full.fullname" . }}
  labels:
{{ include "binance-chain-full.labels" . | indent 4 }}
data:
  config.toml: |-
{{ include "config.toml" . | indent 4 }}
  genesis.json: |-
{{ .Files.Get "genesis.json" | indent 4 }}
  app.toml: |-
{{ .Files.Get "app.toml" | indent 4 }}
