apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "binance-chain-full.fullname" . }}
  labels:
{{ include "binance-chain-full.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "binance-chain-full.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "binance-chain-full.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: configtoml
              mountPath: /bnc/config/config.toml
              subPath: config.toml
            - name: apptoml
              mountPath: /bnc/config/app.toml
              subPath: app.toml
            - name: genesisjson
              mountPath: /bnc/config/genesis.json
              subPath: genesis.json
            - name: data
              mountPath: /bnc
          ports:
            - name: listen
              containerPort: 26656
              protocol: TCP
            - name: httprpc
              containerPort: 26657
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: configtoml
          configMap:
            name: {{ template "binance-chain-full.fullname" . }}
        - name: genesisjson
          configMap:
            name: {{ template "binance-chain-full.fullname" . }}
        - name: apptoml
          configMap:
            name: {{ template "binance-chain-full.fullname" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "binance-chain-full.fullname" . }}
