apiVersion: v1
kind: Service
metadata:
  name: {{ template "binance-chain-full.fullname" . }}
  labels:
{{ include "binance-chain-full.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 26656
      targetPort: listen
      protocol: TCP
      name: listen
    - port: 26657
      targetPort: httprpc
      protocol: TCP
      name: httprpc
  selector:
    app.kubernetes.io/name: {{ include "binance-chain-full.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
