apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "iexec-worker.fullname" . }}
  labels:
{{ include "iexec-worker.labels" . | indent 4 }}
data:
  wallet.json: |-
{{ .Files.Get "wallet.json" | indent 4 }}
