apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "iexec-worker.fullname" . }}
  labels:
{{ include "iexec-worker.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500M
