apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFUzTURJeE56UXpNREFlRncweE9URXdNRFF4T1RNd016QmFGdzB5T1RFd01ERXhPVE13TXpCYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFUzTURJeE56UXpNREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkxwZyt2RS8wV2hid2pRV1hFdmRFeFozOE5oRHRsUnNzRGRsYUpxd1c1SmYKVnBDckh0VzRUYUpxQmJKczBLby91YnRtWnoxVGoxalZaUFJJQXVvc283dWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUJhWGE0a1ZtZytiClNIT3V3SkY5Nk1PZDg0bFR4U2krcktJWEhQSldyb0tpQWlCeHBKcEJGZFc5YW9OZm5YNmZmMWdSN2xTQlJzV1UKQ044VW5raG1rQUxNRHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 17c1a347959e663278bee4d41399c87f
    username: admin
