apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ethereum-light.fullname" . }}
  labels:
{{ include "ethereum-light.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
