apiVersion: v1
kind: Service
metadata:
  name: {{ template "ethereum-light.fullname" . }}
  labels:
{{ include "ethereum-light.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8545
      targetPort: httprpc
      protocol: TCP
      name: httprpc
    - port: 8546
      targetPort: wsrpc
      protocol: TCP
      name: wsrpc
    - port: 30303
      targetPort: listen
      protocol: TCP
      name: listen
    - port: 30303
      targetPort: discovery
      protocol: UDP
      name: discovery
  selector:
    app.kubernetes.io/name: {{ include "ethereum-light.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
